---
title: "Untitled"
author: "Salome Isch, Adriana Ricklin"
date: "10 9 2020"
output: html_document
---

```{r}
library(dplyr)
library(stringr)
library(dplyr)

```


```{r}
getwd()

zaehlung <- read.csv("2019_verkehrszaehlungen_werte_fussgaenger_velo_bereinigt.csv", sep=";", header = TRUE)
colnames(zaehlung)[1] <- "FK_ZAEHLER"

##changing the FK_ZAEHLER to an indicator if bike or pedestrians are measured
zaehlung$FK_ZAEHLER <- as.character(zaehlung$FK_ZAEHLER)
zaehlung$FK_ZAEHLER[zaehlung$FK_ZAEHLER == "U15G3104443"] <- "fussgaenger"
zaehlung$FK_ZAEHLER[zaehlung$FK_ZAEHLER == "U15G3104446"] <- "fussgaenger"
zaehlung$FK_ZAEHLER[zaehlung$FK_ZAEHLER == "ECO09113499"] <- "velo"
zaehlung$FK_ZAEHLER[zaehlung$FK_ZAEHLER == "ECO07091438"] <- "velo"
zaehlung$FK_ZAEHLER <- as.factor(zaehlung$FK_ZAEHLER)
zaehlung$FK_STANDORT <- as.factor(zaehlung$FK_STANDORT)

zaehlung$DATUM <- str_sub(zaehlung$DATUM, end = -4)

#getting the total of movements, independent from their direction
zaehlung[is.na(zaehlung)] <- 0
zaehlung[, "IN"] <- zaehlung[4]+zaehlung[6]
zaehlung[, "OUT"] <- zaehlung[5] + zaehlung[7]
zaehlung[, "UNIDIR"] <- zaehlung[4] + zaehlung [5] + zaehlung[6] +  zaehlung[7]
head(zaehlung)

```

```{r}
wetter <- read.csv("wetter.csv", sep=";", header = TRUE)
#wetter$wind_force_avg_10min <- as.factor(wetter$wind_force_avg_10min)

wetter$timestamp_cet <- str_sub(wetter$timestamp_cet, end = -7)
#aggregated_listWETTER <- aggregate(timestamp_cet ~ wind_force_avg_10min + air_temperature + precipitation, wetter, FUN = "mean")

apply(wetter, MARGIN = 2, FUN = anyNA)
aggregated_Wind <- aggregate(wind_force_avg_10min ~ timestamp_cet, wetter, FUN = mean)
aggregated_Temp <- aggregate(air_temperature ~ timestamp_cet, wetter, FUN = mean)
aggregated_Prec <- aggregate(precipitation ~ timestamp_cet, wetter, sum)

#aggregate <- wetter$aggregated_Wind, wetter$aggregated_Temp, wetter$aggregated_Prec

aggregated_wetter_Wind_Temp <- left_join(aggregated_Wind, aggregated_Temp, by = "timestamp_cet")
aggregated_wetter_Wind_Temp_Prec <- left_join(wetter_Wind_Temp, aggregated_Prec, by = "timestamp_cet")
head(aggregated_wetter_Wind_Temp_Prec)
#View(aggregated_wetter_Wind_Temp_Prec)
#aggregati <- aggregate(wetter$timestamp_cet)
#aggregati

```


```{r}
aggregated_listFK <- aggregate(UNIDIR ~ FK_ZAEHLER + OST + NORD + FK_STANDORT + DATUM, zaehlung, sum)

```
```{r}
#joining both datasets
join_zaehlung_wetter <- left_join(aggregated_listFK, aggregated_wetter_Wind_Temp_Prec, by = c("DATUM" = "timestamp_cet"))
View(join_zaehlung_wetter)
```
